export const GETHOMEDATA = "GETHOMEDATA"
export const SEARCHHOMEDATA = "SEARCHHOMEDATA"

export const GETCHATDATA = "GETCHATDATA"
export const SEARCHCHATDATA = "SEARCHCHATDATA"

export const GETBALANCE = "GETBALANCE"


export const GETUSERS = "GETUSERS"
export const SEARCHUSERS = "SEARCHUSERS"

